version: '3'

services:
  nginx:
    # build: ./nginx
    image: nginx:latest
    ports:
      - "8080:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - app1
      - app2
      - app3

  app1:
    build:
      context: ./project/app1
      dockerfile: Dockerfile
    ports:
      - "8081:3000"

  app2:
    build:
      context: ./project/app2
      dockerfile: Dockerfile
    ports:
      - "8082:3000"

  app3:
    build:
      context: ./project/app3
      dockerfile: Dockerfile
    ports:
      - "8083:3000"
